name: hlc test secret env vars
on: push

jobs:
  test-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo hello, world!
      - name: test secret env
        env: 
          USERNAME: ${{ secrets.USERNAME }}
        run: echo "$USERNAME"
